drivers: sensors: fix missing asm/io.h include in sensors/sensors_ssc.c
../drivers/sensors/sensors_ssc.c:61:12: error: implicit declaration of function ‘__raw_readl’; did you mean ‘__up_read’? [-Werror=implicit-function-declaration]
../drivers/sensors/sensors_ssc.c:275:23: error: implicit declaration of function ‘ioremap’ [-Werror=implicit-function-declaration]
../drivers/sensors/sensors_ssc.c:275:21: warning: assignment makes pointer from integer without a cast [-Wint-conversion]

Signed-off-by: ahmedradaideh <ahmed.radaideh@gmail.com>